

[build.environment]
  NODE_VERSION = "18.14.1"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

 [[plugins.inputs.audits]]
    path = "/"
 [[plugins.inputs.audits]]
    path = "code"
 [[plugins.inputs.audits]]
    path = "music"
 [[plugins.inputs.audits]]
    path = "moodboard"
 [[plugins.inputs.audits]]
    path = "about"
 [[plugins.inputs.audits]]
    path = "notes"
