name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: npm install && npm install -g @lhci/cli@0.8.x
      - name: build
        run: |
          npm run build
          ls build
          ls build/static
          ls build/static/js
          cat build/index.html
      - name: LHCI
        run: lhci autorun
